import pandas as pd
from datetime import datetime
from datetime import timedelta
import requests
import time
import random

#Step 1: Creating Json data----------------------------------------------------------

# Class for data generation

def data_generation():                           # Function creation
    surr_id=random.randint(1,3)                  # generates random numbers between 1 and 3
    speed=random.randint(20,200)                 # generates random numbers between 2 and 200
    date=datetime.today().strftime("%Y-%m-%d")
    time=datetime.now().isoformat()

    return(surr_id,speed,date,time)


#Defining Main Function

if __name__=='__main__':

 #Below URL is copied from the Power BI which is generated after creating the Streaming dataset in power BI
 REST_API_URL='https://api.powerbi.com/beta/50f40674-931c-4d09-ae8a-bb8fde36b912/datasets/7b0520ef-dff2-44a7-ae3a-70d7526d4fc7/rows?noSignUpCheck=1&key=%2FN8klRLR8OwNkrIE1qBTbMp1ZdAovLo6XLnHF8Wm4V6oZsZI%2BqA444YsGeP30kLX0b9JB2F53uka7wjYztFH3Q%3D%3D'

 while True:                                   # for Infinite streaming
    data_raw=[]                                #Empty List
    for i in range(1):                         #For Loop will execute only once
        row=data_generation()                  #Calling the Function
        data_raw.append(row)                   #Appending the data
        print("Raw Data :",data_raw)

    #Set the Header Record
    header=["surr_id","speed","date","time"]   # Mention the Column names for the generated data

    df1=pd.DataFrame(data_raw,columns=header)  #Convert the available data to a dataframe format.

    data_json=bytes(df1.to_json(orient="records"),encoding='utf-8') #Convert the dataframe to Json data format
    print("json data : ",data_json)

#End: Step 1: Creating Json data-----------------------------------------------------
#Step 2: post the data into the Power BI App-----------------------------------------

    req=requests.post(REST_API_URL,data_json)  #posting the Json data into the API URL generated by Power BI
    print("Data posted in Power BI API")

#End : Step 2: post the data into the Power BI App-----------------------------------

