
# # 1. Likelihood Estimator----------------------------------------------
# import numpy as np
# from scipy.optimize import minimize
# import matplotlib.pyplot as plt
# import pandas as pd

# # Sample data from normal distribution with unknown mean (true mean = 5)
# np.random.seed(42)
# data = np.random.normal(loc=5, scale=2, size=100)
# plt.plot(data)
# plt.show()

# # Define negative log-likelihood function (since we minimize)
# def neg_log_likelihood(mu):
#     sigma = 2  # assume known
#     n = len(data)
#     return (n/2) * np.log(2 * np.pi * sigma) + (1/(2 * sigma**2)) * np.sum((data - mu)**2)

# # Use minimize to find MLE estimate
# #Method 1:
# # print(f"neg_log_likelihood(x0=0) : {neg_log_likelihood(0)}")
# # print(f"neg_log_likelihood(x0=1) : {neg_log_likelihood(1)}")
# # print(f"neg_log_likelihood(x0=2) : {neg_log_likelihood(2)}")
# # print(f"neg_log_likelihood(x0=3) : {neg_log_likelihood(3)}")
# # print(f"neg_log_likelihood(x0=4) : {neg_log_likelihood(4)}")

# #Method 2:
# # for i in range(10):
# #     print(f"neg_log_likelihood(x0={i}) : {neg_log_likelihood(i)}")

# #Method 3:
# results = {}
# for i in data:
#     j=neg_log_likelihood(i)
#     #print(f"neg_log_likelihood(x0={i}) : {j}")
#     results[i] = j

# #print(f"results : {results}")

# # Convert to DataFrame
# df = pd.DataFrame(list(results.items()), columns=['Value', 'Output'])
# #df = pd.DataFrame([(k, v[0]) for k, v in results.items()], columns=['Value', 'Output'])
# #print(df)
# df.to_csv('MLE for Normal Distribution output.txt', sep='\t', index=False)

# #Method 4:
# result = minimize(neg_log_likelihood, x0=0)  # initial guess mu=0
# mle_mu = result.x[0]

# print(f"MLE estimate for mean: {mle_mu:.2f}")
# print(f"Sample mean: {np.mean(data):.2f}")

# # Note : The output of MLE Estimate generated by minimize function is 4.79
# # where the same considered from the output file is 4.768703435. the reason for the difference 
# # is the step size which is internally fixed by minimize function



# # End : 1. Likelihood Estimator-----------------------------------------------
# 1.1. MLE for Normal Distribution----------------------------------------------
# import numpy as np
# import matplotlib.pyplot as plt
# from scipy.stats import norm
# from scipy.optimize import minimize

# # Step 1: Simulated Data
# np.random.seed(42)
# data = np.random.normal(loc=5, scale=2, size=100)  # true μ=5, σ=2

# # Step 2: Define Negative Log-Likelihood Function
# def neg_log_likelihood(params):
#     mu, sigma = params[0], params[1]
#     if sigma <= 0:
#         return np.inf  # sigma must be positive
#     return -np.sum(norm.logpdf(data, loc=mu, scale=sigma)) #negative log-likelihood (NLL) for normally distributed data.


# # Step 3: Optimize (Find MLE Estimates)
# initial_guess = [1, 1]
# result = minimize(neg_log_likelihood, initial_guess, bounds=[(None, None), (1e-6, None)])
# mle_mu, mle_sigma = result.x



# # Step 4: Visualization
# x_vals = np.linspace(min(data) - 1, max(data) + 1, 1000)
# pdf_vals = norm.pdf(x_vals, loc=mle_mu, scale=mle_sigma)

# plt.figure(figsize=(10, 6))
# plt.hist(data, bins=20, density=True, alpha=0.6, color='gray', label='Data Histogram')
# plt.plot(x_vals, pdf_vals, 'r-', label=f'MLE Fit: μ={mle_mu:.2f}, σ={mle_sigma:.2f}')
# plt.title('Maximum Likelihood Estimation: Normal Distribution Fit')
# plt.xlabel('x')
# plt.ylabel('Density')
# plt.legend()
# plt.grid(True)
# plt.tight_layout()
# plt.show()

# End : 1.1. MLE for Normal Distribution--------------------------------------------
# #1.2 MLE for Exponential Distribution-----------------------------------------------

# import numpy as np
# import matplotlib.pyplot as plt
# from scipy.stats import expon
# from scipy.optimize import minimize

# # Step 1: Simulated Data from Exponential Distribution (true λ = 2)
# np.random.seed(42)
# data = np.random.exponential(scale=1/2, size=100)  # λ = 2 => scale = 1/λ = 0.5

# # Step 2: Define Negative Log-Likelihood
# def neg_log_likelihood_exp(lambd):
#     if lambd <= 0:
#         return np.inf  # λ must be positive
#     return -np.sum(expon.logpdf(data, scale=1/lambd))

# # Step 3: Optimize to find MLE for λ
# initial_guess = [1]
# result = minimize(neg_log_likelihood_exp, initial_guess, bounds=[(1e-6, None)])
# mle_lambda = result.x[0]

# # Step 4: Visualization
# x_vals = np.linspace(0, np.max(data) + 1, 1000)
# pdf_vals = expon.pdf(x_vals, scale=1/mle_lambda)

# plt.figure(figsize=(10, 6))
# plt.hist(data, bins=20, density=True, alpha=0.6, color='gray', label='Data Histogram')
# plt.plot(x_vals, pdf_vals, 'r-', label=f'MLE Fit: λ = {mle_lambda:.2f}')
# plt.title('Maximum Likelihood Estimation: Exponential Distribution Fit')
# plt.xlabel('x')
# plt.ylabel('Density')
# plt.legend()
# plt.grid(True)
# plt.tight_layout()
# plt.show()

#End : 1.2 MLE for Exponential Distribution-----------------------------------------
# #1.3 MLE for Poisson Distribution----------------------------------------------------
# import numpy as np
# import matplotlib.pyplot as plt
# from scipy.stats import poisson
# from scipy.optimize import minimize

# # Step 1: Simulate Poisson data with true λ = 4
# np.random.seed(42)
# data = np.random.poisson(lam=4, size=100)

# # Step 2: Define negative log-likelihood for Poisson
# def neg_log_likelihood_pois(lambd):
#     if lambd <= 0:
#         return np.inf  # λ must be positive
#     return -np.sum(poisson.logpmf(data, mu=lambd))

# # Step 3: Optimize to find MLE of λ
# initial_guess = [1]
# result = minimize(neg_log_likelihood_pois, initial_guess, bounds=[(1e-6, None)])
# mle_lambda = result.x[0]

# # Step 4: Visualization
# max_val = np.max(data)
# x_vals = np.arange(0, max_val + 5)
# pmf_vals = poisson.pmf(x_vals, mu=mle_lambda)

# plt.figure(figsize=(10, 6))
# plt.hist(data, bins=range(0, max_val + 6), density=True, alpha=0.6, color='gray', align='left', label='Data Histogram')
# plt.plot(x_vals, pmf_vals, 'ro-', label=f'MLE Fit: λ = {mle_lambda:.2f}')
# plt.title('Maximum Likelihood Estimation: Poisson Distribution Fit')
# plt.xlabel('x')
# plt.ylabel('Probability')
# plt.legend()
# plt.grid(True)
# plt.tight_layout()
# plt.show()
## End :1.3 MLE for Poisson Distribution----------------------------------------------------
# why taking Negative log ? example---------------------------------------------------------
# import numpy as np
# import matplotlib.pyplot as plt

# theta = np.linspace(0, 6, 100)
# L = - (theta - 3)**2 + 5         # Likelihood (max at 3)
# neg_L = -L                       # Negative likelihood

# plt.plot(theta, L, label='Likelihood (to maximize)')
# plt.plot(theta, neg_L, label='Negative Likelihood (to minimize)')
# plt.axvline(3, color='red', linestyle='--', label='Max at θ=3')
# plt.legend()
# plt.xlabel('θ')
# plt.ylabel('Value')
# plt.title('Maximizing a function vs Minimizing its negative')
# plt.show()

#End : why taking Negative log ? example------------------------------------------
# 2. Methods of Moment Estimator----------------------------------------------------


# End : 2. Methods of Moment Estimator----------------------------------------
# # 3. MLE, MAP, and Posterior Mean----------------------------------------------

# import numpy as np
# import matplotlib.pyplot as plt
# from scipy.stats import beta

# # Prior: Beta(2, 2)
# a_prior = 2
# b_prior = 2

# # Observed data: 7 heads out of 10 flips
# n = 10
# k = 7

# # Posterior: Beta(a + k, b + n - k)
# a_post = a_prior + k
# b_post = b_prior + (n - k)

# # Theta range for plot
# theta_vals = np.linspace(0, 1, 1000)
# posterior_pdf = beta.pdf(theta_vals, a_post, b_post)

# # Estimators
# theta_map = (a_post - 1) / (a_post + b_post - 2)        # MAP
# theta_mean = a_post / (a_post + b_post)                # Posterior mean
# theta_mle = k / n                                      # MLE

# # Plot
# plt.figure(figsize=(10, 6))
# plt.plot(theta_vals, posterior_pdf, label='Posterior PDF (Beta)', color='blue')
# plt.axvline(theta_map, color='red', linestyle='--', label=f'MAP = {theta_map:.3f}')
# plt.axvline(theta_mean, color='green', linestyle='--', label=f'Posterior Mean = {theta_mean:.3f}')
# plt.axvline(theta_mle, color='orange', linestyle='--', label=f'MLE = {theta_mle:.3f}')
# plt.title('Posterior Distribution and Estimators')
# plt.xlabel('θ (Probability of Heads)')
# plt.ylabel('Density')
# plt.legend()
# plt.grid(True)
# plt.tight_layout()
# plt.show()


# # #What You'll See in the Plot:
# # #The blue curve: Posterior probability distribution 𝑃(𝜃∣𝑋)
# # #Red dashed line: MAP estimate (peak of the posterior)
# # #Green dashed line: Posterior mean (Bayesian estimator)
# # #Orange dashed line: MLE (based only on data, no prior)


# # End : 3. MLE, MAP, and Posterior Mean----------------------------------------
# # Prior and Posterior Distributions--------------------------------------------
# import numpy as np
# import matplotlib.pyplot as plt
# from scipy.stats import beta

# # Prior Beta(2, 2)
# a_prior, b_prior = 2, 2

# # Data: 7 heads, 10 tosses
# n, k = 10, 7

# # Posterior Beta(a + k, b + n - k)
# a_post, b_post = a_prior + k, b_prior + n - k

# theta_vals = np.linspace(0, 1, 1000)

# prior_pdf = beta.pdf(theta_vals, a_prior, b_prior)
# posterior_pdf = beta.pdf(theta_vals, a_post, b_post)

# plt.figure(figsize=(10, 6))
# plt.plot(theta_vals, prior_pdf, label='Prior Beta(2, 2)', color='gray', linestyle='--')
# plt.plot(theta_vals, posterior_pdf, label='Posterior Beta(9, 5)', color='blue')
# plt.title('Prior and Posterior Distributions')
# plt.xlabel('θ (Probability of Heads)')
# plt.ylabel('Density')
# plt.legend()
# plt.grid(True)
# plt.show()

# #End: Prior and Posterior Distributions--------------------------------------------

# #4. Bayesian Estimator----------------------------------------------------------

# #Python example that computes Bayesian estimates for a Bernoulli/Binomial problem (like coin flips) 
# #and visualizes the prior, likelihood, and posterior distributions.

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import beta, binom

# Parameters
alpha_prior = 2
beta_prior = 2
n_trials = 10
x_successes = 7

# Define theta range for plotting
theta = np.linspace(0, 1, 1000)

# Prior distribution
prior = beta.pdf(theta, alpha_prior, beta_prior)

# Likelihood (Binomial pmf for fixed data, but viewed as function of theta)
# We use likelihood function proportional to theta^x * (1-theta)^(n-x)
likelihood = theta**x_successes * (1 - theta)**(n_trials - x_successes)
likelihood /= likelihood.max()  # Normalize for visualization

# Posterior distribution (Beta updated)
alpha_post = alpha_prior + x_successes
beta_post = beta_prior + n_trials - x_successes
posterior = beta.pdf(theta, alpha_post, beta_post)

# Bayesian estimators
posterior_mean = alpha_post / (alpha_post + beta_post)
posterior_mode = (alpha_post - 1) / (alpha_post + beta_post - 2) if alpha_post > 1 and beta_post > 1 else None
mle = x_successes / n_trials

# Plotting
plt.figure(figsize=(10, 6))

plt.plot(theta, prior, label=f'Prior Beta({alpha_prior},{beta_prior})', color='blue')
plt.plot(theta, likelihood, label='Likelihood (scaled)', color='orange')
plt.plot(theta, posterior, label=f'Posterior Beta({alpha_post},{beta_post})', color='green')

plt.axvline(mle, color='black', linestyle='--', label=f'MLE = {mle:.2f}')
plt.axvline(posterior_mean, color='red', linestyle='--', label=f'Posterior Mean = {posterior_mean:.2f}')
if posterior_mode:
    plt.axvline(posterior_mode, color='purple', linestyle='--', label=f'MAP = {posterior_mode:.2f}')

plt.title('Bayesian Estimation of Bernoulli Parameter')
plt.xlabel(r'$\theta$ (Probability of Success)')
plt.ylabel('Density / Scaled Likelihood')
plt.legend()
plt.grid(True)
plt.show()

# # Plots prior Beta distribution (blue)
# # Plots likelihood function (orange), scaled for visualization
# # Plots posterior Beta distribution (green)
# # Vertical lines for:
# # MLE estimate (black dashed)
# # Posterior mean (red dashed)
# # MAP estimate (purple dashed)
#End : 4. Bayesian Estimator----------------------------------------------------------
#__________________*******************************______________________________________

# # Regression Estimators:

# # 1. Ordinary Least Squares

# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# from sklearn.linear_model import LinearRegression
# from sklearn.metrics import mean_squared_error, r2_score
# import statsmodels.api as sm

# # --- Generating Synthetic Data ---
# np.random.seed(42)
# X = 2.5 * np.random.randn(100) + 1.5  # Independent variable
# Y = 0.5 * X + np.random.randn(100) * 0.8  # Dependent variable

# # Converting to DataFrame
# df = pd.DataFrame({'X': X, 'Y': Y})

# # --- Fitting OLS Model ---
# X = sm.add_constant(X)  # Add constant term (intercept)
# ols_model = sm.OLS(Y, X).fit()

# # --- Model Summary ---
# print(ols_model.summary())

# # --- Visualization ---
# plt.figure(figsize=(12, 6))
# plt.scatter(X[:, 1], Y, color='blue', label='Actual Data')
# plt.plot(X[:, 1], ols_model.predict(X), color='red', label='OLS Regression Line')
# plt.xlabel('Independent Variable (X)')
# plt.ylabel('Dependent Variable (Y)')
# plt.title('Ordinary Least Squares (OLS) Regression')
# plt.legend()
# plt.grid()
# plt.show()


# #The OLS regression results show:
# #R-squared: 0.651, meaning the model explains 65% of the variance in Y.
# #Coefficients: Intercept is 0.0747, and slope (X1) is 0.4542, 
# # indicating a positive relationship between X and Y.
# #P-value: 0.000 for X1, suggesting statistical significance.
# #The plot shows actual data (blue) and the fitted OLS regression line (red), 
# # demonstrating a good fit of the model to the data.



# Practical Application: Case Study Interpretation
# In this section, we will explore a practical application of Ordinary Least Squares (OLS)
# regression through a case study on predicting house prices.
# We will break down the OLS summary output step-by-step and offer insights on how to 
# refine the model based on our interpretations with the help of python code that demonstrates 
# how to perform Ordinary Least Squares (OLS) regression to predict house prices using the 
# statsmodels library. This code includes the steps to fit the model, display the summary output, 
# and interpret key metrics.

# import pandas as pd
# import numpy as np
# import statsmodels.api as sm
# import matplotlib.pyplot as plt
# import seaborn as sns

# # Sample dataset creation
# data = {
#     'Size': np.random.randint(500, 4000, 200),  # Size in square feet
#     'Bedrooms': np.random.randint(1, 6, 200),   # Number of bedrooms
#     'Age': np.random.randint(0, 30, 200),       # Age of the house
# }
# data['Price'] = 15000 + data['Size'] * 200 + data['Bedrooms'] * 7500 - data['Age'] * 300 + np.random.normal(0, 10000, 200)

# df = pd.DataFrame(data)

# # Define independent variables (X) and dependent variable (y)
# X = df[['Size', 'Bedrooms', 'Age']]
# y = df['Price']

# # Add a constant term to the independent variables
# X = sm.add_constant(X)
# model = sm.OLS(y, X).fit() # Fit the OLS regression model
# print(model.summary())